In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2= np.array([[1,2.0,3.3],
              [4,5 , 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Create Numpy Arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,(3,5))
random_array

array([[5, 1, 6, 0, 1],
       [3, 0, 3, 1, 8],
       [6, 7, 4, 9, 1]], dtype=int32)

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.9305377 , 0.01761143, 0.59627833],
       [0.06073758, 0.3269121 , 0.17778318],
       [0.10153442, 0.09041896, 0.50668736],
       [0.9265774 , 0.00753838, 0.69209167],
       [0.58606908, 0.4068598 , 0.39541351]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3= np.random.rand(5,3)
random_array_3

array([[0.16652666, 0.17143642, 0.313244  ],
       [0.13774667, 0.81043812, 0.68869829],
       [0.63880615, 0.20097375, 0.85319548],
       [0.09166396, 0.74749992, 0.08615376],
       [0.14076261, 0.84269844, 0.27024478]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4= np.random.randint(10,size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]], dtype=int32)

In [29]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9], dtype=int32)

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

np.int64(1)

In [35]:
a2.shape

(2, 3)

In [36]:
a2[0]

array([1. , 2. , 3.3])

In [37]:
a3.shape

(2, 3, 3)

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a2[1]

array([4. , 5. , 6.5])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [43]:
a3.shape

(2, 3, 3)

In [44]:
# furthest number in size is the nearest in matrix
np.random.seed(seed=99999)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 3, 1, 8, 1],
         [3, 8, 5, 6, 0],
         [6, 0, 4, 0, 9],
         [2, 0, 0, 5, 0]],

        [[0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1],
         [5, 5, 8, 3, 4]],

        [[6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2],
         [0, 7, 2, 8, 1]]],


       [[[2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8],
         [7, 7, 5, 4, 6]],

        [[8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8],
         [1, 5, 5, 5, 6]],

        [[9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3],
         [2, 3, 2, 4, 0]]]], dtype=int32)

In [45]:
a4.size, a4.shape, a4.ndim

(120, (2, 3, 4, 5), 4)

In [46]:
# Get the frist 4 number in the innner most arrays
a4[:,:,:,:1]

array([[[[0],
         [3],
         [6],
         [2]],

        [[0],
         [7],
         [8],
         [5]],

        [[6],
         [6],
         [7],
         [0]]],


       [[[2],
         [3],
         [1],
         [7]],

        [[8],
         [4],
         [7],
         [1]],

        [[9],
         [2],
         [0],
         [2]]]], dtype=int32)

## 4. Manipulating & comparing arrays

### Arithmetic

In [47]:
a1

array([1, 2, 3])

In [48]:
ones= np.ones((3))
ones

array([1., 1., 1.])

In [49]:
a1+ones

array([2., 3., 4.])

In [50]:
a1-ones

array([0., 1., 2.])

In [51]:
a1*ones

array([1., 2., 3.])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [56]:
a1/ones

array([1., 2., 3.])

In [57]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [58]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

### Aggregation

In [59]:
listy_list= [1,2,3]

In [60]:
type(listy_list)

list

In [61]:
sum(listy_list)

6

In [62]:
a1

array([1, 2, 3])

In [63]:
type(a1)

numpy.ndarray

In [64]:
sum(a1)

np.int64(6)

In [65]:
np.sum(a1)

np.int64(6)

# Use python's methods on python  datatype (sum()) and use numpys method in numpy arrays (np.sum())

In [66]:
massive_array=np.random.random(100000)
massive_array.size

100000

In [67]:
massive_array[:10]

array([0.50444862, 0.26663678, 0.74629397, 0.60369925, 0.59567129,
       0.52584989, 0.94380271, 0.53714949, 0.93524783, 0.49521124])

In [68]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

4.69 ms ± 293 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.4 μs ± 415 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
